Update Jenkins_file

diff --git a/Jenkins_file b/Jenkins_file
--- a/Jenkins_file
+++ b/Jenkins_file
@@ -12,17 +12,24 @@ pipeline {
     }
 
     stages {
-        stage('Clear Workspace') {
-            steps {
-                echo 'Clearing workspace...'
-                deleteDir() // Deletes all files in the workspace
-            }
-        }
-
         stage('Checkout Code') {
             steps {
                 echo 'Checking out code from GitHub...'
                 git branch: 'main', url: 'https://github.com/simonebinezer/React.js.git'
+            }
+        }
+
+        stage('Check Zip Installation') {
+            steps {
+                script {
+                    echo 'Checking if zip is installed on the Jenkins server...'
+                    sh """
+                        if ! command -v zip &> /dev/null; then
+                            echo "Error: zip is not installed. Please install zip to continue." >&2
+                            exit 1
+                        fi
+                    """
+                }
             }
         }
 
